######################################################################
#
# File name : cfg_sine_wave_tb_compile.do
# Created on: Thu May 28 02:44:47 -0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../TESTE_CORDIC4.srcs/sources_1/imports/sine/sine_package.vhd" \
"../../../../TESTE_CORDIC4.srcs/sources_1/imports/sine/sine_wave.vhd" \
"../../../../TESTE_CORDIC4.srcs/sources_1/imports/sine/sine_wave_tb.vhd" \
"../../../../TESTE_CORDIC4.srcs/sources_1/imports/sine/sine_wave_cf.vhd" \


quit -force

