-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Tue May 19 02:35:57 2020
-- Host        : Renan-PC running 64-bit major release  (build 9200)
-- Command     : write_vhdl -mode funcsim -nolib -force -file
--               {C:/Users/Renan/Documents/GitHub/Shared-Scripts/Scripts/VHDL/VHDL
--               PROJECTS/VIVADO/sintetizacao_tensao_senoidal/sintetizacao_tensao_senoidal.sim/sim_1/synth/func/xsim/Div_Clk_func_synth.vhd}
-- Design      : sintetizacao_tensao_senoidal
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
