######################################################################
#
# File name : sinus_gen_compile.do
# Created on: Thu May 28 01:12:17 -0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../TESTE_CORDIC3.srcs/sources_1/new/sinus_gen.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

